### ISSUE TITLE
Error in filepath while building

### ISSUE THREAD

**Issue by FranksRobins** [hashicorp/nomad-driver-ecs#15]
Hi, I am trying to build the plugin according to the doc on the README but when I run make build I run into an error about the file paths being invalid due to dots in their name:

Goal: `build nomad ecs driver to try the demo`
Steps: `run **make build** in repo`
Expectation: `make build creates the plugin`
Actual result:  running into the error below:

```
$ make build
go build -o nomad-driver-ecs .
go: extracting github.com/hashicorp/nomad v1.1.0-beta1
-> unzip /home/devops/go/pkg/mod/cache/download/github.com/hashicorp/nomad/@v/v1.1.0-beta1.zip: malformed file path "website/pages/api-docs/[[...page]].jsx": double dot
build github.com/hashicorp/nomad-driver-ecs: cannot load github.com/hashicorp/nomad/client/lib/fifo: unzip /home/devops/go/pkg/mod/cache/download/github.com/hashicorp/nomad/@v/v1.1.0-beta1.zip: malformed file path "website/pages/api-docs/[[...page]].jsx": double dot
make: *** [GNUmakefile:11: build] Error 1
```

Any hint on this? 

```
$ go version
go version go1.13.8 linux/amd64
```

```
$ uname -a
Linux tower1 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

thanks

**Comment by lgfa29** [comment]
Hi @FranksRobins 👋 

I think you will need a more recent version of Go. We just updated the repo to use Go 1.17 and there's a new `make dev` target to help building the driver.

Alternatively, you can also use a pre-compiled binary from https://releases.hashicorp.com/nomad-driver-ecs/0.1.0 instead of building from source.

**Comment by FranksRobins** [comment]
Hi @lgfa29, sorry for this late reply and thank you for your quick one. I have updated my go version and it worked. Glad to have make it work as the tutorial demonstrated! This issue can be closed
